[build-system]
requires = [
    "setuptools",
    "wheel",
    "oldest-supported-numpy",
    "cython>=0.28",
    "raysect @ git+https://github.com/munechika-koyo/source.git@feature/tetrahedra_mesh",
]
build-backend="setuptools.build_meta"
